In [14]:
import pandas as pd
import numpy as np

In [5]:
data=[[2.0,4,8.5,196],[2.4,4,9.6,221],[1.5,4,5.9,136],[3.5,6,11.1,255],[3.5,6,10.6,244],[3.6,6,10.0,230],[3.5,6,10.1,232],[3.7,6,11.1,255],[3.7,6,11.6,267],[2.4,4,9.2,212]]

In [6]:
df=pd.DataFrame(data,columns=['EngineSize','Cylinders','Fuel_Consumption','CO2_Emission'])

In [7]:
df

EngineSize  Cylinders  Fuel_Consumption  CO2_Emission
0         2.0          4               8.5           196
1         2.4          4               9.6           221
2         1.5          4               5.9           136
3         3.5          6              11.1           255
4         3.5          6              10.6           244
5         3.6          6              10.0           230
6         3.5          6              10.1           232
7         3.7          6              11.1           255
8         3.7          6              11.6           267
9         2.4          4               9.2           212

In [8]:
from sklearn.linear_model import LinearRegression

In [32]:
temp=LinearRegression()

In [33]:
temp.fit(np.array(df['EngineSize']).reshape(-1,1),np.array(df['CO2_Emission']).reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
temp.predict(np.array([2]).reshape(-1,1))

array([[183.68725231]])

In [35]:
temp.intercept_

array([99.7836856])

In [36]:
temp.coef_

array([[41.95178336]])

In [ ]:
Y=41.95*X+99.78

In [31]:
np.array(df['EngineSize']).shape

(10,)