In [1]:
import numpy as np
import random

In [2]:
 n,m=int(input('Enter number of tuples')),int(input('Enter number of features'))

Enter number of tuples3
Enter number of features5


In [3]:
r=[]
q=[]
for i in range(n):
    q.append(list(map(int,input().split())))
r=np.array(q)
rr=r       

1 0 1 0 1
1 0 0 1 0
0 1 1 0 1


In [4]:
y=[]
for i in range(n):
    print("enter disese ",i+1)
    disease=y.append(input())
for i in range(n):
    print(rr[i],y[i])


enter disese  1
diaria
enter disese  2
malaria
enter disese  3
fever
[1 0 1 0 1] diaria
[1 0 0 1 0] malaria
[0 1 1 0 1] fever


In [5]:
print('enter mathcing elements')
while(True):
    a=np.array(list(map(int,input().split())))
    for i in range(len(rr)):
        if np.array_equal(rr[i],a):
            print("disease is",y[i])
            k=1
            break
    if(k==0):
        print("Doesn't exist")
    print("Do you want to continue(Y/N)")
    choice=input()
    if(choice!='Y'):
        break

enter mathcing elements
1 0 1 0 1
disease is diaria
Do you want to continue(Y/N)
N


In [7]:
cluster={}
for i in range(len(rr)):
    count=np.sum(rr[i])
    cluster[count]=cluster.get(count,[])+[y[i]]

print(cluster)    

{3: ['diaria', 'fever'], 2: ['malaria']}


In [13]:
a={}
for i in cluster:
    if len(cluster[i])>1:
        for j in cluster[i]:
            m=y.index(j)
            f=rr[m][1]+rr[m][2]+rr[m][4]
            a[j]=f
print(a)

{'diaria': 2, 'fever': 3}
