In [1]:
import numpy as np

In [2]:
x_original=np.array([[1,0,1,0,1],[1,0,0,1,0],[0,1,1,0,1],[1,1,1,0,0],[1,0,0,0,1]])
print(x_original)

[[1 0 1 0 1]
 [1 0 0 1 0]
 [0 1 1 0 1]
 [1 1 1 0 0]
 [1 0 0 0 1]]


In [4]:
y=["Malaria","Dengue","Jaundice","Typhoid","high fever"]
for i in range(len(x_original)):
    print(x_original[i],y[i])
x=x_original

[1 0 1 0 1] Malaria
[1 0 0 1 0] Dengue
[0 1 1 0 1] Jaundice
[1 1 1 0 0] Typhoid
[1 0 0 0 1] high fever


**Identifying Matchings**

In [6]:
while(True):
    print("Enter the features in 0's and 1's")
    check=np.array([int(i) for i in input().split()])
    for i in range(len(x)):
        if np.array_equal(x[i],check):
            print("You are suffering from",y[i])
            break
    else:
        print("There is no data in the database.")
    stop=input('Do You want to continue y/n')
    if stop=="n":
        break

Enter the features in 0's and 1's
1 0 0 0 1
You are suffering from high fever
Do You want to continue y/ny
Enter the features in 0's and 1's
1 0 0 1 0
You are suffering from Dengue
Do You want to continue y/nn


**Dividing into clusters**

In [10]:
cluster={"cluster1":[],"cluster2":[]}
for i in range(len(x)):
    ones=x[i].sum()
    if ones>=3:
        cluster["cluster1"].append([y[i],ones])
    else:
        cluster["cluster2"].append([y[i],ones])
for i in cluster:
    print(i)
    for j in cluster[i]:
        print(j[0],j[1])
    print()

cluster1
Malaria 3
Jaundice 3
Typhoid 3

cluster2
Dengue 2
high fever 2



**Classification among the Clusters**

In [13]:
for i in cluster:
    print(i)
    for j in cluster[i]:
        index=y.index(j[0])
        prominent=x[index][1]+x[index][2]+x[index][4]
        print(j[0],prominent)
    print()

cluster1
Malaria 2
Jaundice 3
Typhoid 2

cluster2
Dengue 0
high fever 1

