In [4]:
import numpy
my_array=numpy.array([[1,2,3],[4,5,6],[7,8,9]])

1. You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.


In [5]:
print(numpy.zeros([3,3], dtype = numpy.int)) 
print(numpy.ones([3,3], dtype = numpy.int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


2. You are given a 2-D array with dimensions  N X M
Your task is to perform the min function over axis 1 and then find the max of that.

In [7]:
print(numpy.max(numpy.min(my_array, axis = 1)))

7


3. You are given a 2-D array with dimensions  N X M
Your task is to perform the SUM function over axis 0 and then find the PRODUCT of that.

In [8]:
print(numpy.prod( numpy.sum( my_array, axis = 0 )))

3240


4. You are given a 2-D array of size N X M

Your task is to find:

    The mean along axis 1
    The var along axis 0
    The std along axis None


In [9]:
print(numpy.mean(my_array, axis = 1))
print(numpy.var(my_array, axis = 0))
print(numpy.std(my_array, axis = None))

[2. 5. 8.]
[6. 6. 6.]
2.581988897471611


5. Write a program to implement y=x^2+logx without using loops. x may be a scalar or vector or tensor (n-dimensional array).

In [13]:
x=numpy.arange(1,10)
y=x*x+numpy.log(x)
print(y)

[ 1.          4.69314718 10.09861229 17.38629436 26.60943791 37.79175947
 50.94591015 66.07944154 83.19722458]


6. Implement (X- μ)/ σ ,where μ is mean of x and  σ is the standard deviation of X, without using loops. X may be a scalar or vector or tensor.

In [14]:
x=numpy.arange(1,10)
mue=numpy.mean(x)
sigma=numpy.std(x)
print((x-mue)/sigma)

[-1.54919334 -1.161895   -0.77459667 -0.38729833  0.          0.38729833
  0.77459667  1.161895    1.54919334]
