# **NumPy** 
is a Python package which stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

# **NumPy – A Replacement for MatLab**
NumPy is often used along with packages like SciPy (Scientific Python) and Mat−plotlib (plotting library). This combination is widely used as a replacement for MatLab, a popular platform for technical computing.

The most important object defined in NumPy is an N-dimensional array type called **ndarray**. It **describes the collection of items of the same type**. Items in the collection can be accessed using a zero-based index.

The basic ndarray is created using an array function in NumPy as follows:

**numpy.array**

The array constructor has keys parameters like

 **dtype**:Desired data type of array, optional.

 **ndmin**:Specifies minimum dimensions of resultant array


<p>NumPy supports a much greater variety of numerical types than Python does. The following table shows different scalar data types defined in NumPy.</p>
<table class="table table-bordered">
<tr>
<th style="text-align:center;">Sr.No.</th>
<th style="text-align:center;">Data Types &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><p><b>bool_</b></p>
<p>Boolean (True or False) stored as a byte</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><p><b>int_</b></p>
<p>Default integer type (same as C long; normally either int64 or int32)</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><p><b>intc</b></p>
<p>Identical to C int (normally int32 or int64)</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><p><b>intp</b></p>
<p>Integer used for indexing (same as C ssize_t; normally either int32 or int64)</p>
</td>
</tr>
<tr>
<td class="ts">5</td>
<td><p><b>int8</b></p>
<p>Byte (-128 to 127)</p>
</td>
</tr>
<tr>
<td class="ts">6</td>
<td><p><b>int16</b></p>
<p>Integer (-32768 to 32767)</p>
</td>
</tr>
<tr>
<td class="ts">7</td>
<td><p><b>int32</b></p>
<p>Integer (-2147483648 to 2147483647)</p>
</td>
</tr>
<tr>
<td class="ts">8</td>
<td><p><b>int64</b></p>
<p>Integer (-9223372036854775808 to 9223372036854775807)</p>
</td>
</tr>
<tr>
<td class="ts">9</td>
<td><p><b>uint8</b></p>
<p>Unsigned integer (0 to 255)</p>
</td>
</tr>
<tr>
<td class="ts">10</td>
<td><p><b>uint16</b></p>
<p>Unsigned integer (0 to 65535)</p>
</td>
</tr>
<tr>
<td class="ts">11</td>
<td><p><b>uint32</b></p>
<p>Unsigned integer (0 to 4294967295)</p>
</td>
</tr>
<tr>
<td class="ts">12</td>
<td><p><b>uint64</b></p>
<p>Unsigned integer (0 to 18446744073709551615)</p>
</td>
</tr>
<tr>
<td class="ts">13</td>
<td><p><b>float_</b></p>
<p>Shorthand for float64</p>
</td>
</tr>
<tr>
<td class="ts">14</td>
<td><p><b>float16</b></p>
<p>Half precision float: sign bit, 5 bits exponent, 10 bits mantissa</p>
</td>
</tr>
<tr>
<td class="ts">15</td>
<td><p><b>float32</b></p>
<p>Single precision float: sign bit, 8 bits exponent, 23 bits mantissa</p>
</td>
</tr>
<tr>
<td class="ts">16</td>
<td><p><b>float64</b></p>
<p>Double precision float: sign bit, 11 bits exponent, 52 bits mantissa</p>
</td>
</tr>
<tr>
<td class="ts">17</td>
<td><p><b>complex_</b></p>
<p>Shorthand for complex128</p>
</td>
</tr>
<tr>
<td class="ts">18</td>
<td><p><b>complex64</b></p>
<p>Complex number, represented by two 32-bit floats (real and imaginary components)</p>
</td>
</tr>
<tr>
<td class="ts">19</td>
<td><p><b>complex128</b></p>
<p>Complex number, represented by two 64-bit floats 
(real and imaginary components)</p>
</td>
</tr>
</table>




In [0]:
#Example1
import numpy as np 
a = np.array([1,2,3]) 
print(a)

In [0]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print (a)

In [0]:
# minimum dimensions 
import numpy as np 
a = np.array([[1, 2], [3,4], [5,6]]) 
print (a[2][0])

In [0]:
# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5]) 
print (a[4])
print([0][4])  #Throws error since it is single dimentional array only.

In [0]:
# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
print (a[0][4])

In [0]:
# minimum dimensions 
import numpy as np 
a = np.array([[1, 2, 3,4,5],[6,7,8,9,10]]) 
print (a[1][4])
print(a[1,4])

In [0]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j]


# **NumPy - Array Attributes**

In [0]:
#Example 1

import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print (a.shape)

In [0]:
#Example 2

# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a)

In [0]:
#Example 3

import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)

# **ndarray.ndim**

This array attribute returns the number of array dimensions.

In [0]:
#Example 1
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(24) 
print (a)
print(a[4])

In [0]:
#Example 2
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
a.ndim  

# now reshape it 
b = a.reshape(2,4,3) 
print (b) 
# b is having three dimensions

# **numpy.itemsize**

This array attribute returns the length of each element of array in bytes.

In [0]:
#Example1
# dtype of array is int8 (1 byte) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

In [0]:
#Example 2
# dtype of array is now float32 (4 bytes) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.float32) 
print (x.itemsize)

**ndarray.shape**

This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

In [0]:
#Example 1
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)

In [0]:
#Example 2
# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print a 

In [0]:
#Example 3
#NumPy also provides a reshape function to resize an array.
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print b


In [0]:
#Example 4

# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
a.ndim  

# now reshape it 
b = a.reshape(2,4,3) 
print b 
# b is having three dimensions

# **NumPy - Array Creation Routines**

A new ndarray object can be constructed by any of the following array creation routines

In [0]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print (x)

In [0]:
# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(5) 
print (x)

#For Integer values
x = np.zeros((5,), dtype = np.int) 
print (x)

In [0]:
# array of five ones. Default dtype is float 
import numpy as np 
x = np.ones(5) 
print (x)

x = np.ones([2,2], dtype = int) 
print (x)

In [0]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.1124604  0.63891814]
 [0.57217836 0.91065852]]


# **NumPy - Array From Existing Data**

**numpy.asarray**

This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.

***numpy.asarray(a, dtype = None, order = None)***

The parameters are as follows:

**a:** Input data in any form such as **list**, **list of tuples**, **tuples**, **tuple of tuples** or **tuple of lists**

	
**dtype:** By default, the data type of input data is applied to the resultant ndarray

**order:** C (row major) or F (column major). C is default

In [0]:
#Example 1
# convert list to ndarray 
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print (a)

In [0]:
#Example 2
# dtype is set 
import numpy as np 

x = [1,2,3]
a = np.asarray(x, dtype = float) 
print (a)

In [0]:
#Example 3
# ndarray from tuple 
import numpy as np 

x = (1,2,3) 
a = np.asarray(x) 
print (a)

In [0]:
#ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)

# **NumPy - Array From Numerical Ranges**

**numpy.arange**

This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows

**numpy.arange(start, stop, step, dtype)**



In [0]:
#Example 1
import numpy as np 
x = np.arange(5) 
print (x)

In [0]:
# dtype set 
x = np.arange(5, dtype = float)
print (x)

In [0]:
# start, stop and set parameters.
x = np.arange(10,20,2) 
print (x)

# **NumPy - Indexing & Slicing**

A Python slice object is constructed by giving **start**, **stop**, and **step** parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

In [0]:
import numpy as np 
a = np.arange(10) 
print(a)
s = slice(2,7,1) 
print (a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]


In [0]:
a = np.arange(10) 
print(a)
s = slice(2,7,2) 
print (a[s])

In the above example, an ndarray object is prepared by arange() function. Then a slice object is defined with start, stop, and step values 2, 7, and 2 respectively. When this slice object is passed to the ndarray, a part of it starting with index 2 up to 7 with a step of 2 is sliced.


The same result can also be obtained by giving the slicing parameters separated by a colon : (**start:stop:step**) directly to the ndarray object.

In [0]:

a = np.arange(10) 
b = a[2:7:2] #This is also similar to slice(2,7,1)
print (b)

In [0]:
# slice single item 
#import numpy as np 

a = np.arange(10) 
b = a[5] 
print (b)

In [0]:
# slice items starting from index 
#import numpy as np 
a = np.arange(10) 
print a[2:]

In [0]:
# slice items between indexes 
#import numpy as np 
a = np.arange(10) 
print a[2:5]

In [0]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)

# slice items starting from index
print ('Now we will slice the array from the index a[1:]') 
print (a[1:])

Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. If ellipsis is used at the row position, it will return an ndarray comprising of items in rows.

(**...** ,**col**)--> This notation extracts ndarray from given column

(**row**, **...**)--> This notation extracts ndarray from given row

(**...** ,**col \:**)--> This notation extracts ndarray from given column onwards

(**row \:** , **...**)--> This notation extracts ndarray from given row onwards

In [0]:
NumPy - Broadcastinga = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print (a) 
print ('\n')

# this returns array of items in the second column 
print ('The items in the second column are:')
print (a[...,1])
print ('\n')

# Now we will slice all items from the second row 
print ('The items in the second row are:')
print (a[1,...])
print ('\n')  

# Now we will slice all items from column 1 onwards 
print ('The items from column 1 onwards are:')
print (a[...,1:])

print ('The items from row 1 onwards are:')
print (a[1:,...])
print ('\n')

In [0]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]. The assignment of 77 to b[0,0] changes a[0,1]
                 #Since, the location of b[0,0]=a[0,1] are same.
print(a[0, 1])   # Prints "77"
print(a)

In [0]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"
row_r2 = a[1:, :]  # Rank 2 view of the second row of a
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

In [0]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

# **NumPy - Broadcasting**

The term **broadcasting** refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. 

Arithmetic operations on arrays are usually done on corresponding elements. 

If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [0]:
import numpy as np 
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


In [0]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:')
print (a) 
print ('\n')
   
print ('Second array:')
print (b) 
print ('\n')
   
print ('First Array + Second Array')
print (a + b)

# **NumPy - Arithmetic Operations**

In [0]:
import numpy as np 
a = np.arange(9,dtype ='f').reshape(3,3) 

print ('First array:')
print (a) 
print ('\n')

print ('Second array:')
b = np.array([10,10,10]) 
print (b)
print ('\n')

print ('Add the two arrays:')
print (np.add(a,b))
print ('\n')

print ('Subtract the two arrays:')
print (np.subtract(a,b))
print ('\n')

print ('Multiply the two arrays:')
print (np.multiply(a,b))
print ('\n')

print ('Divide the two arrays:')
print (np.divide(a,b))

In [0]:
#numpy.power()

import numpy as np 
a = np.array([10,100,1000]) 

print ('Our array is:')
print (a)
print ('\n')

print ('Applying power function:')
print (np.power(a,2))
print ('\n')  

print ('Second array:')
b = (np.array([1,2,3]))
print (b)
print ('\n')

print ('Applying power function again:')
print (np.power(a,b))

In [0]:
#numpy.mod() and numpy.remainder()
import numpy as np 
a = np.array([10,20,30]) 
b = np.array([3,5,7]) 

print ('First array:')
print (a)
print ('\n')

print ('Second array:')
print (b)
print ('\n')

print ('Applying mod() function:')
print (np.mod(a,b))
print ('\n')

print ('Applying remainder() function:')
print (np.remainder(a,b))

# **NumPy - Statistical Functions**

NumPy has quite a few useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc.



In [0]:
#numpy.amin() and numpy.amax()
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print ('Our array is:')
print (a)
print ('\n')

print ('Applying amin() function:')
print (np.amin(a,1))
print ('\n')

print ('Applying amin() function again:')
print (np.amin(a,0))
print ('\n')

print ('Applying amax() function:')
print (np.amax(a))
print ('\n')

print ('Applying amax() function again:')
print (np.amax(a, axis = 0))

# **NumPy - Matplotlib**

In [0]:
import numpy as np 
from matplotlib import pyplot as plt 

x = np.arange(1,11) 
y = 2 * x + 5 
plt.title("Matplotlib demo") 
plt.xlabel("x axis caption") 
plt.ylabel("y axis caption") 
plt.plot(x,y) 
plt.show()

In [0]:
import numpy as np 
from matplotlib import pyplot as plt 

x = np.arange(1,11) 
y = 2 * x + 5 
plt.title("Matplotlib demo") 
plt.xlabel("x axis caption") 
plt.ylabel("y axis caption") 
plt.plot(x,y,"ob") 
plt.show() 

In [0]:
from matplotlib import pyplot as plt 
x = [5,8,10] 
y = [12,16,6]  

x2 = [6,9,11] 
y2 = [6,15,7] 
plt.bar(x, y, align = 'center') 
plt.bar(x2, y2, color = 'g', align = 'center') 
plt.title('Bar graph') 
plt.ylabel('Y axis') 
plt.xlabel('X axis')  

plt.show()